// <auto-generated />
using System;
using AutoClick.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoClick.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AutoClick.Models.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanderinAdquirido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carroceria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cilindrada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorExterior")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorInterior")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Combustible")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailPropietario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtrasAntiRobo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtrasExterior")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtrasInterior")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtrasMultimedia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtrasRendimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtrasSeguridad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenPrincipal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenesUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroPasajeros")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroPuertas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlacaVehiculo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanVisibilidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Traccion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicacionExacta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorFiscal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VideosUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Ano");

                    b.HasIndex("Canton");

                    b.HasIndex("EmailPropietario");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("Marca");

                    b.HasIndex("Modelo");

                    b.HasIndex("PlacaVehiculo")
                        .IsUnique()
                        .HasFilter("PlacaVehiculo IS NOT NULL AND PlacaVehiculo != ''");

                    b.HasIndex("Provincia");

                    b.ToTable("Autos");
                });

            modelBuilder.Entity("AutoClick.Models.Usuario", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreAgencia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.HasIndex("NombreAgencia");

                    b.HasIndex("NumeroTelefono");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AutoClick.Models.Auto", b =>
                {
                    b.HasOne("AutoClick.Models.Usuario", "Propietario")
                        .WithMany()
                        .HasForeignKey("EmailPropietario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Propietario");
                });
#pragma warning restore 612, 618
        }
    }
}
